### ISSUE TITLE
common.h.in missing

### ISSUE THREAD

**Issue by psteinb** [UoB-HPC/GPU-STREAM#21]
Hi,
I just downloaded v3.0 and during cmake execution, I get:
```
$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
...
CMake Error: File /home/steinbac/development/gpu-stream/GPU-STREAM-3.0/common.h.in does not exist.
CMake Error at CMakeLists.txt:25 (configure_file):
  configure_file Problem configuring file
No CMAKE_BUILD_TYPE specified, defaulting to 'Release'
...
-- Configuring incomplete, errors occurred!
See also "/home/steinbac/development/gpu-stream/GPU-STREAM-3.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/steinbac/development/gpu-stream/GPU-STREAM-3.0/build/CMakeFiles/CMakeError.log".
```
this error comes from (CMakeLists.txt#L25)[https://github.com/UoB-HPC/GPU-STREAM/blob/master/CMakeLists.txt#L25]

**Comment by jrprice** [comment]
Fixed in caf367f.

The build system is generally quite broken at the moment, and we haven't been using CMake at all ourselves for a long time. We're still trying to work out how to fix the build system properly for all the models, and are leaning towards having a separate Makefile per model.

**Comment by psteinb** [comment]
may I know the reason of this? maybe I can be of help writing cmake find modules?

**Comment by jrprice** [comment]
With the exception of the models that are well supported by CMake (e.g. CUDA, OpenCL, HIP), lots of the implementations have proven extremely tricky to get working in a portable manner, given the wide variety of different platforms and compilers that we're targeting.

In theory CMake is supposed to be good for this, and I'm sure it's possible to get everything working within CMake, but so far it's proven more effort than it's worth (most of the time we find that just typing the compile command manually is easier than trying to fiddle CMake to do the right thing). We haven't ruled CMake out completely though. It may just be that we need to sit down and write proper CMake modules for each model that deal with all of the issues that we run into.

**Comment by psteinb** [comment]
thanks for your open reply. I am still a bit confused. last time I 
checked, GPU-Stream was *nix/macOS only. Given that your minimum cmake 
version is 3.3 and upwards, it's a bit unclear to me what gives you so 
much trouble. You are mostly going to link dynamically and don't care 
about rpaths etc. Can you give me an example what gave you the most trouble?

to be honest, GPU-Stream is between a rock and a hard place for me. You 
want to link to as many as parallel programming interfaces as possible 
(both low-level like Cuda/OpenCL/OpenMP/HCC/... and library based 
Raja/Kokkos/...) to achieve high coverage and yet want to make building 
as easy as possible. With my own libraries, I've found this to be very 
hard.

the c++ world is simply not there yet. cmake is advancing to become a 
standard build tool that some other tools even start to build open 
(IDEs, binary web-based distribution tools, ...) and yet, many libraries 
and compilers do not come with cmake find modules of their own. on top, 
cmake's success is based on a fundamental crime within it's own right 
... they created yet another domain specific scripting language (and not 
even a very good one). but as it is sometimes, it's the best we have so 
far and it will be around for a very long time.

**Comment by tomdeakin** [comment]
You perfectly capture the difficulties we are having in your second paragraph! There are a number of other Issues that users have submitted describing their pain with the CMake system currently in place, which definitely needs some improvement.

One issue of our own is that some model and compiler combinations require knowledge of the particular device we which to run on in order to compile correctly. For example, we may want to specify the `-arch` flag when building CUDA code, and with OpenACC with the PGI compiler we may need to specify `-ta=nvidia:cc50` or `-ta=multicore` or other variants.

We also will want to build 1 binary per model, and some models require different compilers to do this. For example, we might need GCC to build the CUDA binary, PGI to build the OpenACC version, or other combinations of compiler vendors. Having all these compilers loaded in your path could produce conflicts, but also my experience with CMake is that it works with a single compiler at once.

We've found that come models which already use CMake interfere with the building of other models. For example RAJA needs to build `main.cpp` file with `nvcc` but setting this in the CMake system caused the CUDA build to fail. Kokkos drops out to a Makefile as we needed to include another Makefile which is provided by the library itself. A potential solution to this is to put all the code for the different models in their own subdirectory and having a CMakeLists.txt file for each other them.

Our ultimate aim is something simple which correctly builds all the models for a particular device with a particular choice of compiler in one go, setting all the correct flags.

**Comment by Ruyk** [comment]
Our experience with CMake has been always painful. If you are targeting Linux systems, a Makefile mechanism per programming model may be easier to maintain, but more difficult to configure (How many parameters and paths would you have to store?). 
However, CMake will give you more flexibility in terms of importing other modules and may be easy for people to contribute and integrate with other tools.
One possibility would be to have individual cmake files per programming model, and then a common generic one which includes all the other ones as subprojects or ExternalProjects.
