### ISSUE TITLE
Cannot find source file OMP3Stream.cpp

### ISSUE THREAD

**Issue by psteinb** [UoB-HPC/GPU-STREAM#23]
Hi,
just checked out caf367f8fbb58fa4f1bc6185269bc95f96980ec8 and did:

```
$ cd repo
$ mkdir build && cd build
$ cmake ..
#...
- Configuring done
CMake Error at CMakeLists.txt:111 (add_executable):
  Cannot find source file:

    OMP3Stream.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: gpu-stream-omp3
CMake Error: Cannot determine link language for target "gpu-stream-omp3".
-- Generating done
-- Build files have been written to: /projects/hpcsupport/steinbac/development/gpu-stream/build
```
I see `OMPStream.cpp` in the source directory, but `OMP3Stream.cpp` as well as `OMP45Stream.cpp` are missing.

**Comment by tomdeakin** [comment]
We have merged `OMP3Stream.cpp` and `OMP45Stream.cpp` into `OMPStream.cpp`. We did this to check that it was viable to have a single source OpenMP code which targeting CPUs and GPUs and use preprocessor switches to choose the correct pragmas.

We haven't updated the CMake system for a while so this file change won't have made it in there. Our regular usage of the benchmark doesn't use CMake to build so the `CMakeLists.txt` file lags a bit, but we are working on getting the build system fixed.

You should be able to build using the `OMPStream.cpp` instead. You need to specify `-DOMP` to tell GPU-STREAM that it should ask for the OpenMP version, rather than the different defines for OpenMP 3 and 4.5 we had previously. By default this file uses the standard `#pragma omp parallel for` as in `OMP3Stream.cpp`, but if you also specify `-DOMP_TARGET_GPU` it switches out to the `#pragma omp target` directives as was in the `OMP45Stream.cpp` file. Generally we build for OpenMP like:
```
c++ -std=c++11 -O3 -DOMP main.cpp OMPStream.cpp -fopenmp
```
