### ISSUE TITLE
Make fails for RAJA

### ISSUE THREAD

**Issue by tomdeakin** [UoB-HPC/GPU-STREAM#9]
CUDA and RAJA interfeer in CMakeLists.txt

**Comment by DavidPoliakoff** [comment]
Hey, I'm running into this as well. I get RAJA to build if I add

  set_source_files_properties(main.cpp PROPERTIES CUDA_SOURCE_PROPERTY_FORMAT OBJ)

But then the OMP3 build crashes. Don't know whether it's possible to fix along those lines.

**Comment by tomdeakin** [comment]
We haven't found a way of getting RAJA to play nicely with CMake; we also find that CUDA breaks if you add that line. There are lots of other issues with the CMake too as lots of flags are missing for many of the models. We are just working out what it going to work best and what is needed across the range of devices across the platforms we use.

In the mean time, we're building manually with this command:
`nvcc --expt-extended-lambda -arch=sm_52 -O3 -std=c++11 -DUSE_RAJA main.cpp RAJAStream.cpp -x cu -L$RAJA_PATH/lib -lRAJA  -Xcompiler -fopenmp`

You may also have to make sure `common.h` exists. It just contains
`#define VERSION_STRING 2.1`

**Comment by DavidPoliakoff** [comment]
Hey Tom, thanks for the update. 

In our current implementation we have an (everchanging) custom FindCUDA.cmake which we use to handle a lot of ugliness (including how to do CUDA compilation with the Clang CUDA compiler). I might file an issue on our repo about this, it seems like the kind of thing that ought to work.

Honestly, some of the problem is that we're all reconciling different CUDA oddities, and resolving them in different ways. Let me get back to this when I have time, but thanks again, you've brought a lot of good feedback to the project, it's highly appreciated

**Comment by tomdeakin** [comment]
Fixed in v3.1. We've moved away from CMake so can better control how we build against RAJA. New version works for all combinations we tried in our usual results matrix.
